"""Wd

Revision ID: 1b645d4d1c2e
Revises: fe09e2b2a678
Create Date: 2025-10-23 19:04:36.312585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b645d4d1c2e'
down_revision: Union[str, Sequence[str], None] = 'fe09e2b2a678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('phone_number', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
