"""Fixing nane

Revision ID: 9f3b966a0a18
Revises: 665ea2cde142
Create Date: 2025-10-21 19:26:50.830059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3b966a0a18'
down_revision: Union[str, Sequence[str], None] = '665ea2cde142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('building', sa.Column('address', sa.String(length=50), nullable=True))
    op.drop_column('building', 'nane')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('nane', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('building', 'address')
    op.drop_column('building', 'name')
    # ### end Alembic commands ###
