"""Phone Number Changing

Revision ID: fe09e2b2a678
Revises: 2a2a663072a4
Create Date: 2025-10-23 18:23:55.136882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe09e2b2a678'
down_revision: Union[str, Sequence[str], None] = '2a2a663072a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('phone_number', sa.Integer(), nullable=True))
    op.drop_column('organization', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('number', sa.INTEGER(), nullable=True))
    op.drop_column('organization', 'phone_number')
    # ### end Alembic commands ###
